// AURXON Authoritative RBAC Permissions Registry & Mathematical Mappings
import { ScopeLevel } from './types';

export interface ActionDefinition {
  action: string;
  domain: string;
  resource: string;
  description: string;
  defaultScope: ScopeLevel;
  isSensitive: boolean;
  requiresFourEyesApproval: boolean;
}

export const ACTION_DEFINITIONS: Record<string, ActionDefinition> = {
  // --- Students ---
  'students.view': {
    action: 'students.view',
    domain: 'students',
    resource: 'STUDENT',
    description: 'View student profile and academic enrollment within authorized scope',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'students.view_sensitive': {
    action: 'students.view_sensitive',
    domain: 'students',
    resource: 'STUDENT',
    description: 'View sensitive background, medical records, and disciplinary notes',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'students.view_own': {
    action: 'students.view_own',
    domain: 'students',
    resource: 'STUDENT',
    description: 'Self-service view of own student profile or verified child records',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'students.create': {
    action: 'students.create',
    domain: 'students',
    resource: 'STUDENT',
    description: 'Admit and enroll new students into institutional records',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'students.update': {
    action: 'students.update',
    domain: 'students',
    resource: 'STUDENT',
    description: 'Update academic and demographic student information',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'students.archive': {
    action: 'students.archive',
    domain: 'students',
    resource: 'STUDENT',
    description: 'Graduate, transfer, or archive student academic enrollment',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },

  // --- Attendance ---
  'attendance.view': {
    action: 'attendance.view',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'View class and section daily attendance rosters',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'attendance.view_own': {
    action: 'attendance.view_own',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'View self or verified child attendance percentage and logs',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'attendance.mark': {
    action: 'attendance.mark',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'Record live daily roll-call attendance for assigned classes',
    defaultScope: 'SECTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'attendance.correct': {
    action: 'attendance.correct',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'Request or perform retrospective attendance record corrections',
    defaultScope: 'SECTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'attendance.approve': {
    action: 'attendance.approve',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'Approve historical attendance correction adjustments',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },

  // --- Examinations & Marks ---
  'examinations.view': {
    action: 'examinations.view',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'View examination timetables, grade rules, and assessment schedules',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'examinations.view_own': {
    action: 'examinations.view_own',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'View self or verified child official report cards and marks',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'examinations.create': {
    action: 'examinations.create',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'Create terms, assessment schemes, and examination timetables',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'examinations.enter_marks': {
    action: 'examinations.enter_marks',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'Enter term and periodic assessment marks for assigned subjects',
    defaultScope: 'SUBJECT',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'examinations.review': {
    action: 'examinations.review',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'Review mark entries, grade distributions, and moderation',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'examinations.publish': {
    action: 'examinations.publish',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'Formally publish official report cards and marksheets to student portals',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },

  // --- Fees & Financials ---
  'fees.view': {
    action: 'fees.view',
    domain: 'fees',
    resource: 'FEE',
    description: 'View fee structures, student ledger dues, and collection statistics',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'fees.view_own': {
    action: 'fees.view_own',
    domain: 'fees',
    resource: 'FEE',
    description: 'View self or child fee invoices, pending dues, and payment history',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'fees.create': {
    action: 'fees.create',
    domain: 'fees',
    resource: 'FEE',
    description: 'Configure fee structures, installment heads, and concessions',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'fees.collect': {
    action: 'fees.collect',
    domain: 'fees',
    resource: 'FEE',
    description: 'Collect student fee payment and issue formal ledger entry',
    defaultScope: 'BRANCH',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'fees.receipt': {
    action: 'fees.receipt',
    domain: 'fees',
    resource: 'FEE',
    description: 'Print and download official institutional fee vouchers',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'fees.adjust': {
    action: 'fees.adjust',
    domain: 'fees',
    resource: 'FEE',
    description: 'Request concession, waiver, scholarship, or ledger adjustment',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'fees.refund': {
    action: 'fees.refund',
    domain: 'fees',
    resource: 'FEE',
    description: 'Execute or request refund of student caution money or fees',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'fees.approve': {
    action: 'fees.approve',
    domain: 'fees',
    resource: 'FEE',
    description: 'Approve financial fee adjustments, waivers, and refund transactions',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },

  // --- Staff & HR ---
  'staff.view': {
    action: 'staff.view',
    domain: 'staff',
    resource: 'STAFF',
    description: 'View staff directory, designations, and departmental rosters',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'staff.view_sensitive_hr': {
    action: 'staff.view_sensitive_hr',
    domain: 'staff',
    resource: 'STAFF',
    description: 'View confidential salaries, bank account details, and PAN/Aadhaar',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'staff.create': {
    action: 'staff.create',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Initiate staff recruitment, profile screening, and onboarding',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'staff.update': {
    action: 'staff.update',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Update employee qualifications, experience, and contact details',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'staff.verify_document': {
    action: 'staff.verify_document',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Verify or reject candidate educational and identity proofs',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'staff.assign_responsibility': {
    action: 'staff.assign_responsibility',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Assign class teacher, exam coordinator, or HOD duties',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'staff.transfer': {
    action: 'staff.transfer',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Transfer staff between institutional campuses or branches',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'staff.provision_account': {
    action: 'staff.provision_account',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Provision institutional system login account with temporary credentials',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },

  // --- Academics & Timetable ---
  'academics.view': {
    action: 'academics.view',
    domain: 'academics',
    resource: 'ACADEMICS',
    description: 'View curriculum, subject syllabus, and timetable slots',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'academics.manage': {
    action: 'academics.manage',
    domain: 'academics',
    resource: 'ACADEMICS',
    description: 'Configure subjects, syllabus, academic calendar, and class structures',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'timetable.view': {
    action: 'timetable.view',
    domain: 'timetable',
    resource: 'TIMETABLE',
    description: 'View master timetable and faculty schedules',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'timetable.view_own': {
    action: 'timetable.view_own',
    domain: 'timetable',
    resource: 'TIMETABLE',
    description: 'View personal teaching schedule or student class schedule',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'timetable.manage': {
    action: 'timetable.manage',
    domain: 'timetable',
    resource: 'TIMETABLE',
    description: 'Generate, adjust, and allocate timetable slots and room assignments',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },

  // --- Governance, Roles & Platform ---
  'roles.view': {
    action: 'roles.view',
    domain: 'roles',
    resource: 'ROLE',
    description: 'View active roles, assignments, and effective permission matrix',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'roles.manage': {
    action: 'roles.manage',
    domain: 'roles',
    resource: 'ROLE',
    description: 'Customize organizational role permissions and policies',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'approvals.act': {
    action: 'approvals.act',
    domain: 'approvals',
    resource: 'APPROVAL',
    description: 'Approve or reject four-eyes workflow submissions (Requester != Approver)',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'audit.view': {
    action: 'audit.view',
    domain: 'audit',
    resource: 'AUDIT',
    description: 'Inspect immutable system mutation logs and security audit trail',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'license.view': {
    action: 'license.view',
    domain: 'license',
    resource: 'ORGANIZATION',
    description: 'View tenant subscription tier, renewal date, and seat quotas',
    defaultScope: 'ORGANIZATION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'license.manage': {
    action: 'license.manage',
    domain: 'license',
    resource: 'ORGANIZATION',
    description: 'Manage platform licensing, renewal extensions, and tier overrides',
    defaultScope: 'PLATFORM',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'announcement.create': {
    action: 'announcement.create',
    domain: 'communication',
    resource: 'COMMUNICATION',
    description: 'Broadcast notices and announcements to students and staff',
    defaultScope: 'SECTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'announcement.view': {
    action: 'announcement.view',
    domain: 'communication',
    resource: 'COMMUNICATION',
    description: 'Read published school and campus circulars',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
};

// --- BASE FUNCTIONAL ROLES MATRIX ---
export const BASE_ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ['*'],

  ORG_ADMIN: [
    'students.view',
    'students.create',
    'students.update',
    'students.archive',
    'students.view_sensitive',
    'attendance.view',
    'attendance.mark',
    'attendance.correct',
    'attendance.approve',
    'examinations.view',
    'examinations.create',
    'examinations.review',
    'examinations.publish',
    'fees.view',
    'fees.create',
    'fees.collect',
    'fees.receipt',
    'fees.adjust',
    'fees.refund',
    'fees.approve',
    'staff.view',
    'staff.view_sensitive_hr',
    'staff.create',
    'staff.update',
    'staff.verify_document',
    'staff.assign_responsibility',
    'staff.transfer',
    'staff.provision_account',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'roles.view',
    'roles.manage',
    'approvals.act',
    'audit.view',
    'license.view',
    'announcement.create',
    'announcement.view',
  ],

  PRINCIPAL: [
    'students.view',
    'students.view_sensitive',
    'students.create',
    'students.update',
    'attendance.view',
    'attendance.approve',
    'examinations.view',
    'examinations.create',
    'examinations.review',
    'examinations.publish',
    'fees.view',
    'fees.receipt',
    'staff.view',
    'staff.update',
    'staff.verify_document',
    'staff.assign_responsibility',
    'staff.provision_account',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'roles.view',
    'approvals.act',
    'audit.view',
    'license.view',
    'announcement.create',
    'announcement.view',
  ],

  VICE_PRINCIPAL: [
    'students.view',
    'students.update',
    'attendance.view',
    'attendance.approve',
    'examinations.view',
    'examinations.review',
    'fees.view',
    'fees.receipt',
    'staff.view',
    'staff.update',
    'staff.verify_document',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'roles.view',
    'approvals.act',
    'audit.view',
    'announcement.create',
    'announcement.view',
  ],

  BRANCH_HEAD: [
    'students.view',
    'students.create',
    'students.update',
    'attendance.view',
    'attendance.mark',
    'attendance.approve',
    'examinations.view',
    'fees.view',
    'fees.collect',
    'fees.receipt',
    'staff.view',
    'staff.update',
    'academics.view',
    'timetable.view',
    'approvals.act',
    'audit.view',
    'announcement.create',
    'announcement.view',
  ],

  ACADEMIC_COORDINATOR: [
    'students.view',
    'attendance.view',
    'examinations.view',
    'examinations.create',
    'examinations.review',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'announcement.create',
    'announcement.view',
  ],

  EXAM_COORDINATOR: [
    'students.view',
    'examinations.view',
    'examinations.create',
    'examinations.review',
    'examinations.publish',
    'academics.view',
    'announcement.create',
    'announcement.view',
  ],

  TEACHER: [
    'students.view',
    'attendance.view',
    'attendance.mark',
    'examinations.view',
    'examinations.enter_marks',
    'academics.view',
    'timetable.view',
    'timetable.view_own',
    'announcement.view',
  ],

  FACULTY: [
    'students.view',
    'attendance.view',
    'attendance.mark',
    'examinations.view',
    'examinations.enter_marks',
    'academics.view',
    'timetable.view',
    'timetable.view_own',
    'announcement.view',
  ],

  ACCOUNTANT: [
    'students.view',
    'fees.view',
    'fees.create',
    'fees.collect',
    'fees.receipt',
    'fees.adjust',
    'audit.view',
    'announcement.view',
  ],

  FINANCE_MANAGER: [
    'students.view',
    'fees.view',
    'fees.create',
    'fees.collect',
    'fees.receipt',
    'fees.adjust',
    'fees.refund',
    'fees.approve',
    'approvals.act',
    'audit.view',
    'announcement.view',
  ],

  HR_MANAGER: [
    'staff.view',
    'staff.view_sensitive_hr',
    'staff.create',
    'staff.update',
    'staff.verify_document',
    'staff.transfer',
    'staff.provision_account',
    'approvals.act',
    'audit.view',
    'announcement.create',
    'announcement.view',
  ],

  FRONT_OFFICE: [
    'students.view',
    'students.create',
    'fees.receipt',
    'timetable.view',
    'announcement.view',
  ],

  PARENT: [
    'students.view_own',
    'attendance.view_own',
    'examinations.view_own',
    'fees.view_own',
    'timetable.view_own',
    'announcement.view',
  ],

  STUDENT: [
    'students.view_own',
    'attendance.view_own',
    'examinations.view_own',
    'fees.view_own',
    'timetable.view_own',
    'announcement.view',
  ],
};

// --- RESPONSIBILITY EXTENSION PERMISSIONS ---
export const RESPONSIBILITY_PERMISSIONS: Record<string, string[]> = {
  CLASS_TEACHER: [
    'attendance.mark',
    'attendance.correct',
    'students.view',
    'examinations.review',
    'announcement.create',
  ],
  SUBJECT_TEACHER: [
    'examinations.enter_marks',
    'academics.view',
  ],
  EXAM_COORDINATOR: [
    'examinations.create',
    'examinations.review',
    'examinations.publish',
  ],
  ACADEMIC_COORDINATOR: [
    'academics.manage',
    'timetable.manage',
  ],
  CLASS_MONITOR: [
    // CR is strictly restricted: NO marks, NO attendance, NO fees modification!
    'announcement.create',
    'timetable.view_own',
  ],
};

export const ALL_PERMISSIONS = Object.keys(ACTION_DEFINITIONS);
