// AURXON Authoritative RBAC Permissions Registry & Mathematical Mappings
import { ScopeLevel } from './types';

export interface ActionDefinition {
  action: string;
  domain: string;
  resource: string;
  description: string;
  defaultScope: ScopeLevel;
  isSensitive: boolean;
  requiresFourEyesApproval: boolean;
}

export const ACTION_DEFINITIONS: Record<string, ActionDefinition> = {
  // --- Students ---
  'students.view': {
    action: 'students.view',
    domain: 'students',
    resource: 'STUDENT',
    description: 'View student profile and academic enrollment within authorized scope',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'students.view_sensitive': {
    action: 'students.view_sensitive',
    domain: 'students',
    resource: 'STUDENT',
    description: 'View sensitive background, medical records, and disciplinary notes',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'students.view_own': {
    action: 'students.view_own',
    domain: 'students',
    resource: 'STUDENT',
    description: 'Self-service view of own student profile or verified child records',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'students.create': {
    action: 'students.create',
    domain: 'students',
    resource: 'STUDENT',
    description: 'Admit and enroll new students into institutional records',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'students.update': {
    action: 'students.update',
    domain: 'students',
    resource: 'STUDENT',
    description: 'Update academic and demographic student information',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'students.archive': {
    action: 'students.archive',
    domain: 'students',
    resource: 'STUDENT',
    description: 'Graduate, transfer, or archive student academic enrollment',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },

  // --- Attendance ---
  'attendance.view': {
    action: 'attendance.view',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'View class and section daily attendance rosters',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'attendance.view_own': {
    action: 'attendance.view_own',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'View self or verified child attendance percentage and logs',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'attendance.mark': {
    action: 'attendance.mark',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'Record live daily roll-call attendance for assigned classes',
    defaultScope: 'SECTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'attendance.correct': {
    action: 'attendance.correct',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'Request or perform retrospective attendance record corrections',
    defaultScope: 'SECTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'attendance.approve': {
    action: 'attendance.approve',
    domain: 'attendance',
    resource: 'ATTENDANCE',
    description: 'Approve historical attendance correction adjustments',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },

  // --- Examinations & Marks ---
  'examinations.view': {
    action: 'examinations.view',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'View examination timetables, grade rules, and assessment schedules',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'examinations.view_own': {
    action: 'examinations.view_own',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'View self or verified child official report cards and marks',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'examinations.create': {
    action: 'examinations.create',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'Create terms, assessment schemes, and examination timetables',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'examinations.enter_marks': {
    action: 'examinations.enter_marks',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'Enter term and periodic assessment marks for assigned subjects',
    defaultScope: 'SUBJECT',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'examinations.review': {
    action: 'examinations.review',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'Review mark entries, grade distributions, and moderation',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'examinations.publish': {
    action: 'examinations.publish',
    domain: 'examinations',
    resource: 'EXAMINATION',
    description: 'Formally publish official report cards and marksheets to student portals',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },

  // --- Fees & Financials ---
  'fees.view': {
    action: 'fees.view',
    domain: 'fees',
    resource: 'FEE',
    description: 'View fee structures, student ledger dues, and collection statistics',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'fees.view_own': {
    action: 'fees.view_own',
    domain: 'fees',
    resource: 'FEE',
    description: 'View self or child fee invoices, pending dues, and payment history',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'fees.create': {
    action: 'fees.create',
    domain: 'fees',
    resource: 'FEE',
    description: 'Configure fee structures, installment heads, and concessions',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'fees.collect': {
    action: 'fees.collect',
    domain: 'fees',
    resource: 'FEE',
    description: 'Collect student fee payment and issue formal ledger entry',
    defaultScope: 'BRANCH',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'fees.receipt': {
    action: 'fees.receipt',
    domain: 'fees',
    resource: 'FEE',
    description: 'Print and download official institutional fee vouchers',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'fees.adjust': {
    action: 'fees.adjust',
    domain: 'fees',
    resource: 'FEE',
    description: 'Request concession, waiver, scholarship, or ledger adjustment',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'fees.refund': {
    action: 'fees.refund',
    domain: 'fees',
    resource: 'FEE',
    description: 'Execute or request refund of student caution money or fees',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'fees.approve': {
    action: 'fees.approve',
    domain: 'fees',
    resource: 'FEE',
    description: 'Approve financial fee adjustments, waivers, and refund transactions',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },

  // --- Staff & HR ---
  'staff.view': {
    action: 'staff.view',
    domain: 'staff',
    resource: 'STAFF',
    description: 'View staff directory, designations, and departmental rosters',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'staff.view_sensitive_hr': {
    action: 'staff.view_sensitive_hr',
    domain: 'staff',
    resource: 'STAFF',
    description: 'View confidential salaries, bank account details, and PAN/Aadhaar',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'staff.create': {
    action: 'staff.create',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Initiate staff recruitment, profile screening, and onboarding',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'staff.update': {
    action: 'staff.update',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Update employee qualifications, experience, and contact details',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'staff.verify_document': {
    action: 'staff.verify_document',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Verify or reject candidate educational and identity proofs',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'staff.assign_responsibility': {
    action: 'staff.assign_responsibility',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Assign class teacher, exam coordinator, or HOD duties',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'staff.transfer': {
    action: 'staff.transfer',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Transfer staff between institutional campuses or branches',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'staff.provision_account': {
    action: 'staff.provision_account',
    domain: 'staff',
    resource: 'STAFF',
    description: 'Provision institutional system login account with temporary credentials',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },

  // --- Academics & Timetable ---
  'academics.view': {
    action: 'academics.view',
    domain: 'academics',
    resource: 'ACADEMICS',
    description: 'View curriculum, subject syllabus, and timetable slots',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'academics.manage': {
    action: 'academics.manage',
    domain: 'academics',
    resource: 'ACADEMICS',
    description: 'Configure subjects, syllabus, academic calendar, and class structures',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'timetable.view': {
    action: 'timetable.view',
    domain: 'timetable',
    resource: 'TIMETABLE',
    description: 'View master timetable and faculty schedules',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'timetable.view_own': {
    action: 'timetable.view_own',
    domain: 'timetable',
    resource: 'TIMETABLE',
    description: 'View personal teaching schedule or student class schedule',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'timetable.manage': {
    action: 'timetable.manage',
    domain: 'timetable',
    resource: 'TIMETABLE',
    description: 'Generate, adjust, and allocate timetable slots and room assignments',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },

  // --- Governance, Roles & Platform ---
  'roles.view': {
    action: 'roles.view',
    domain: 'roles',
    resource: 'ROLE',
    description: 'View active roles, assignments, and effective permission matrix',
    defaultScope: 'INSTITUTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'roles.manage': {
    action: 'roles.manage',
    domain: 'roles',
    resource: 'ROLE',
    description: 'Customize organizational role permissions and policies',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'approvals.act': {
    action: 'approvals.act',
    domain: 'approvals',
    resource: 'APPROVAL',
    description: 'Approve or reject four-eyes workflow submissions (Requester != Approver)',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'audit.view': {
    action: 'audit.view',
    domain: 'audit',
    resource: 'AUDIT',
    description: 'Inspect immutable system mutation logs and security audit trail',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'license.view': {
    action: 'license.view',
    domain: 'license',
    resource: 'ORGANIZATION',
    description: 'View tenant subscription tier, renewal date, and seat quotas',
    defaultScope: 'ORGANIZATION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'license.manage': {
    action: 'license.manage',
    domain: 'license',
    resource: 'ORGANIZATION',
    description: 'Manage platform licensing, renewal extensions, and tier overrides',
    defaultScope: 'PLATFORM',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'announcement.create': {
    action: 'announcement.create',
    domain: 'communication',
    resource: 'COMMUNICATION',
    description: 'Broadcast notices and announcements to students and staff',
    defaultScope: 'SECTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'announcement.view': {
    action: 'announcement.view',
    domain: 'communication',
    resource: 'COMMUNICATION',
    description: 'Read published school and campus circulars',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },

  // --- Leave Management ---
  'leave.view': {
    action: 'leave.view',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'View institutional faculty and student leave registers and balances',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'leave.view_own': {
    action: 'leave.view_own',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'View personal leave balance quotas, history, and status',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'leave.apply_staff': {
    action: 'leave.apply_staff',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Submit formal faculty/staff leave request with reason and duration',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'leave.review_coordinator': {
    action: 'leave.review_coordinator',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Review and approve short (1-day) teacher absences and timetable adjustments',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'leave.review_hod': {
    action: 'leave.review_hod',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Review departmental faculty leave applications and recommend substitutes',
    defaultScope: 'DEPARTMENT',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'leave.approve_vp': {
    action: 'leave.approve_vp',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Approve 2-3 day faculty leaves and timetable reallocations',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'leave.approve_principal': {
    action: 'leave.approve_principal',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Final institutional authority to approve long, special, or sensitive leaves',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
  'leave.manage_policy': {
    action: 'leave.manage_policy',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Configure institutional leave quotas, types, and approval thresholds',
    defaultScope: 'ORGANIZATION',
    isSensitive: true,
    requiresFourEyesApproval: true,
  },
  'leave.apply_student': {
    action: 'leave.apply_student',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Submit student leave request with parent confirmation',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'leave.approve_student': {
    action: 'leave.approve_student',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Class teacher or school authority approve student leave',
    defaultScope: 'SECTION',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'leave.cancel': {
    action: 'leave.cancel',
    domain: 'leave',
    resource: 'LEAVE',
    description: 'Withdraw or cancel requested/approved leave with reason',
    defaultScope: 'OWN',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },

  // --- Reports & Exports ---
  'reports.view': {
    action: 'reports.view',
    domain: 'reports',
    resource: 'REPORT',
    description: 'Inspect operational, academic, attendance, and fee aggregate reports',
    defaultScope: 'BRANCH',
    isSensitive: false,
    requiresFourEyesApproval: false,
  },
  'reports.export': {
    action: 'reports.export',
    domain: 'reports',
    resource: 'REPORT',
    description: 'Export official school records to CSV, Excel, or PDF format',
    defaultScope: 'INSTITUTION',
    isSensitive: true,
    requiresFourEyesApproval: false,
  },
};

// --- BASE FUNCTIONAL ROLES MATRIX ---
export const BASE_ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ['*'],

  ORG_ADMIN: [
    'students.view',
    'students.create',
    'students.update',
    'students.archive',
    'students.view_sensitive',
    'attendance.view',
    'attendance.mark',
    'attendance.correct',
    'attendance.approve',
    'examinations.view',
    'examinations.create',
    'examinations.review',
    'examinations.publish',
    'fees.view',
    'fees.create',
    'fees.collect',
    'fees.receipt',
    'fees.adjust',
    'fees.refund',
    'fees.approve',
    'staff.view',
    'staff.view_sensitive_hr',
    'staff.create',
    'staff.update',
    'staff.verify_document',
    'staff.assign_responsibility',
    'staff.transfer',
    'staff.provision_account',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'roles.view',
    'roles.manage',
    'approvals.act',
    'audit.view',
    'license.view',
    'announcement.create',
    'announcement.view',
  ],

  PRINCIPAL: [
    'students.view',
    'students.view_sensitive',
    'students.create',
    'students.update',
    'attendance.view',
    'attendance.approve',
    'examinations.view',
    'examinations.create',
    'examinations.review',
    'examinations.publish',
    'fees.view',
    'fees.receipt',
    'staff.view',
    'staff.update',
    'staff.verify_document',
    'staff.assign_responsibility',
    'staff.provision_account',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'roles.view',
    'approvals.act',
    'audit.view',
    'license.view',
    'announcement.create',
    'announcement.view',
  ],

  VICE_PRINCIPAL: [
    'students.view',
    'students.update',
    'attendance.view',
    'attendance.approve',
    'examinations.view',
    'examinations.review',
    'fees.view',
    'fees.receipt',
    'staff.view',
    'staff.update',
    'staff.verify_document',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'roles.view',
    'approvals.act',
    'audit.view',
    'announcement.create',
    'announcement.view',
  ],

  BRANCH_HEAD: [
    'students.view',
    'students.create',
    'students.update',
    'attendance.view',
    'attendance.mark',
    'attendance.approve',
    'examinations.view',
    'fees.view',
    'fees.collect',
    'fees.receipt',
    'staff.view',
    'staff.update',
    'academics.view',
    'timetable.view',
    'approvals.act',
    'audit.view',
    'announcement.create',
    'announcement.view',
  ],

  ACADEMIC_COORDINATOR: [
    'students.view',
    'attendance.view',
    'examinations.view',
    'examinations.create',
    'examinations.review',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'announcement.create',
    'announcement.view',
  ],

  EXAM_COORDINATOR: [
    'students.view',
    'examinations.view',
    'examinations.create',
    'examinations.review',
    'examinations.publish',
    'academics.view',
    'announcement.create',
    'announcement.view',
  ],

  TEACHER: [
    'students.view',
    'attendance.view',
    'attendance.mark',
    'examinations.view',
    'examinations.enter_marks',
    'academics.view',
    'timetable.view',
    'timetable.view_own',
    'announcement.view',
  ],

  FACULTY: [
    'students.view',
    'attendance.view',
    'attendance.mark',
    'examinations.view',
    'examinations.enter_marks',
    'academics.view',
    'timetable.view',
    'timetable.view_own',
    'announcement.view',
  ],

  ACCOUNTANT: [
    'students.view',
    'staff.view',
    'fees.view',
    'fees.create',
    'fees.collect',
    'fees.receipt',
    'fees.adjust',
    'audit.view',
    'announcement.view',
  ],

  FINANCE_MANAGER: [
    'students.view',
    'fees.view',
    'fees.create',
    'fees.collect',
    'fees.receipt',
    'fees.adjust',
    'fees.refund',
    'fees.approve',
    'approvals.act',
    'audit.view',
    'announcement.view',
  ],

  HR_MANAGER: [
    'staff.view',
    'staff.view_sensitive_hr',
    'staff.create',
    'staff.update',
    'staff.verify_document',
    'staff.transfer',
    'staff.provision_account',
    'leave.view',
    'leave.manage_policy',
    'approvals.act',
    'audit.view',
    'reports.view',
    'reports.export',
    'announcement.create',
    'announcement.view',
  ],

  HR_OFFICER: [
    'staff.view',
    'staff.create',
    'staff.update',
    'staff.verify_document',
    'leave.view',
    'leave.view_own',
    'reports.view',
    'announcement.view',
  ],

  SCHOOL_ADMIN: [
    'students.view',
    'students.create',
    'students.update',
    'students.archive',
    'attendance.view',
    'attendance.approve',
    'examinations.view',
    'fees.view',
    'fees.receipt',
    'staff.view',
    'staff.create',
    'staff.update',
    'staff.provision_account',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.manage',
    'roles.view',
    'audit.view',
    'reports.view',
    'reports.export',
    'announcement.create',
    'announcement.view',
  ],

  DIRECTOR: [
    'students.view',
    'students.view_sensitive',
    'attendance.view',
    'examinations.view',
    'examinations.review',
    'examinations.publish',
    'fees.view',
    'fees.approve',
    'staff.view',
    'staff.view_sensitive_hr',
    'academics.view',
    'academics.manage',
    'roles.view',
    'approvals.act',
    'audit.view',
    'license.view',
    'reports.view',
    'reports.export',
    'announcement.create',
    'announcement.view',
  ],

  HEAD_OF_SCHOOL: [
    'students.view',
    'students.view_sensitive',
    'attendance.view',
    'examinations.view',
    'examinations.review',
    'examinations.publish',
    'fees.view',
    'fees.approve',
    'staff.view',
    'staff.view_sensitive_hr',
    'academics.view',
    'academics.manage',
    'roles.view',
    'approvals.act',
    'audit.view',
    'license.view',
    'reports.view',
    'reports.export',
    'announcement.create',
    'announcement.view',
  ],

  HOD: [
    'students.view',
    'attendance.view',
    'examinations.view',
    'examinations.review',
    'academics.view',
    'academics.manage',
    'timetable.view',
    'timetable.view_own',
    'leave.view_own',
    'leave.review_hod',
    'reports.view',
    'announcement.create',
    'announcement.view',
  ],

  DISCIPLINE_COORDINATOR: [
    'students.view',
    'students.view_sensitive',
    'attendance.view',
    'announcement.create',
    'announcement.view',
    'reports.view',
  ],

  ADMISSION_COUNSELLOR: [
    'students.view',
    'students.create',
    'students.update',
    'fees.receipt',
    'timetable.view',
    'announcement.view',
  ],

  IT_ADMIN: [
    'students.view',
    'staff.view',
    'staff.provision_account',
    'roles.view',
    'audit.view',
    'license.view',
    'announcement.view',
  ],

  FRONT_OFFICE: [
    'students.view',
    'students.create',
    'fees.receipt',
    'timetable.view',
    'announcement.view',
  ],

  CLASS_TEACHER: [
    'students.view',
    'attendance.view',
    'attendance.mark',
    'attendance.correct',
    'examinations.view',
    'examinations.enter_marks',
    'examinations.review',
    'academics.view',
    'timetable.view',
    'timetable.view_own',
    'leave.view_own',
    'leave.apply_staff',
    'leave.approve_student',
    'announcement.create',
    'announcement.view',
  ],

  SUBJECT_TEACHER: [
    'students.view',
    'attendance.view',
    'attendance.mark',
    'examinations.view',
    'examinations.enter_marks',
    'academics.view',
    'timetable.view',
    'timetable.view_own',
    'leave.view_own',
    'leave.apply_staff',
    'announcement.view',
  ],

  SPECIAL_EDUCATOR: [
    'students.view',
    'students.view_sensitive',
    'academics.view',
    'timetable.view_own',
    'leave.view_own',
    'leave.apply_staff',
    'announcement.view',
  ],

  COUNSELLOR: [
    'students.view',
    'students.view_sensitive',
    'academics.view',
    'timetable.view_own',
    'leave.view_own',
    'leave.apply_staff',
    'announcement.view',
  ],

  LIBRARIAN: [
    'students.view',
    'staff.view',
    'timetable.view',
    'announcement.view',
  ],

  LAB_ASSISTANT: [
    'students.view',
    'timetable.view',
    'timetable.view_own',
    'announcement.view',
  ],

  SPORTS_COORDINATOR: [
    'students.view',
    'attendance.view',
    'timetable.view',
    'announcement.create',
    'announcement.view',
  ],

  FEE_COLLECTOR: [
    'students.view',
    'fees.view',
    'fees.collect',
    'fees.receipt',
    'announcement.view',
  ],

  TRANSPORT_MANAGER: [
    'students.view',
    'attendance.view',
    'announcement.create',
    'announcement.view',
  ],

  TRANSPORT_COORDINATOR: [
    'students.view',
    'announcement.view',
  ],

  PARENT: [
    'students.view_own',
    'attendance.view_own',
    'examinations.view_own',
    'fees.view_own',
    'timetable.view_own',
    'leave.view_own',
    'leave.apply_student',
    'announcement.view',
  ],

  STUDENT: [
    'students.view_own',
    'attendance.view_own',
    'examinations.view_own',
    'fees.view_own',
    'timetable.view_own',
    'leave.view_own',
    'leave.apply_student',
    'announcement.view',
  ],

  CLASS_MONITOR: [
    // CR is strictly restricted: NO marks, NO attendance, NO fees modification!
    'announcement.create',
    'timetable.view_own',
    'announcement.view',
  ],
};

// --- RESPONSIBILITY EXTENSION PERMISSIONS ---
export const RESPONSIBILITY_PERMISSIONS: Record<string, string[]> = {
  CLASS_TEACHER: [
    'attendance.mark',
    'attendance.correct',
    'students.view',
    'examinations.review',
    'leave.approve_student',
    'announcement.create',
  ],
  SUBJECT_TEACHER: [
    'examinations.enter_marks',
    'academics.view',
  ],
  HOD: [
    'examinations.review',
    'academics.manage',
    'leave.review_hod',
    'announcement.create',
  ],
  EXAM_COORDINATOR: [
    'examinations.create',
    'examinations.review',
    'examinations.publish',
  ],
  ACADEMIC_COORDINATOR: [
    'academics.manage',
    'timetable.manage',
    'leave.review_coordinator',
  ],
  DISCIPLINE_COMMITTEE: [
    'students.view_sensitive',
    'announcement.create',
  ],
  CLASS_MONITOR: [
    // CR is strictly advisory: NO marks, NO attendance, NO fees modification!
    'announcement.create',
    'timetable.view_own',
  ],
};

// --- CENTRAL MODULE ACCESS MATRIX (SECTION 44 STANDARD) ---
// Module -> Role -> AccessLevel
import { AccessLevel } from './types';

export const CENTRAL_MODULE_ACCESS_MATRIX: Record<string, Record<string, AccessLevel>> = {
  STUDENT: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'APPROVE',
    VICE_PRINCIPAL: 'EDIT',
    SCHOOL_ADMIN: 'EDIT',
    ORG_ADMIN: 'EDIT',
    TEACHER: 'VIEW',
    FACULTY: 'VIEW',
    CLASS_TEACHER: 'VIEW',
    ACCOUNTANT: 'VIEW',
    HR_MANAGER: 'VIEW',
    PARENT: 'VIEW',
    STUDENT: 'VIEW',
    FRONT_OFFICE: 'CREATE',
    ADMISSION_COUNSELLOR: 'CREATE',
  },
  ATTENDANCE: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'APPROVE',
    VICE_PRINCIPAL: 'APPROVE',
    SCHOOL_ADMIN: 'EDIT',
    ORG_ADMIN: 'EDIT',
    TEACHER: 'EDIT',
    FACULTY: 'EDIT',
    CLASS_TEACHER: 'EDIT',
    ACCOUNTANT: 'NONE',
    HR_MANAGER: 'VIEW',
    PARENT: 'VIEW',
    STUDENT: 'VIEW',
    CLASS_MONITOR: 'NONE', // CR CANNOT mark attendance
  },
  MARKS: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'REVIEW',
    VICE_PRINCIPAL: 'REVIEW',
    EXAM_COORDINATOR: 'REVIEW',
    HOD: 'REVIEW',
    SCHOOL_ADMIN: 'VIEW',
    ORG_ADMIN: 'VIEW',
    TEACHER: 'EDIT',
    FACULTY: 'EDIT',
    SUBJECT_TEACHER: 'EDIT',
    CLASS_TEACHER: 'REVIEW',
    ACCOUNTANT: 'NONE',
    HR_MANAGER: 'NONE',
    PARENT: 'VIEW',
    STUDENT: 'VIEW',
    CLASS_MONITOR: 'NONE', // CR CANNOT edit marks
  },
  RESULTS: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'PUBLISH',
    VICE_PRINCIPAL: 'REVIEW',
    EXAM_COORDINATOR: 'REVIEW',
    HOD: 'REVIEW',
    SCHOOL_ADMIN: 'VIEW',
    ORG_ADMIN: 'VIEW',
    TEACHER: 'SUBMIT',
    FACULTY: 'SUBMIT',
    ACCOUNTANT: 'NONE',
    HR_MANAGER: 'NONE',
    PARENT: 'VIEW',
    STUDENT: 'VIEW',
  },
  FEES: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'APPROVE',
    VICE_PRINCIPAL: 'VIEW',
    FINANCE_MANAGER: 'APPROVE',
    ACCOUNTANT: 'EDIT',
    FEE_COLLECTOR: 'CREATE',
    SCHOOL_ADMIN: 'VIEW',
    ORG_ADMIN: 'APPROVE',
    TEACHER: 'NONE',
    FACULTY: 'NONE',
    HR_MANAGER: 'NONE',
    PARENT: 'VIEW',
    STUDENT: 'VIEW',
  },
  STAFF: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'VIEW',
    VICE_PRINCIPAL: 'VIEW',
    SCHOOL_ADMIN: 'EDIT',
    ORG_ADMIN: 'EDIT',
    HR_MANAGER: 'EDIT',
    HR_OFFICER: 'EDIT',
    TEACHER: 'VIEW',
    FACULTY: 'VIEW',
    ACCOUNTANT: 'NONE',
    PARENT: 'NONE',
    STUDENT: 'NONE',
  },
  SALARY: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'VIEW_SENSITIVE',
    VICE_PRINCIPAL: 'NONE',
    FINANCE_MANAGER: 'VIEW_SENSITIVE',
    HR_MANAGER: 'VIEW_SENSITIVE',
    SCHOOL_ADMIN: 'NONE',
    ORG_ADMIN: 'VIEW_SENSITIVE',
    TEACHER: 'NONE',
    FACULTY: 'NONE',
    ACCOUNTANT: 'NONE',
    PARENT: 'NONE',
    STUDENT: 'NONE',
  },
  LEAVE: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'APPROVE',
    VICE_PRINCIPAL: 'APPROVE',
    ACADEMIC_COORDINATOR: 'REVIEW',
    HOD: 'REVIEW',
    SCHOOL_ADMIN: 'EDIT',
    ORG_ADMIN: 'APPROVE',
    HR_MANAGER: 'EDIT',
    TEACHER: 'SUBMIT',
    FACULTY: 'SUBMIT',
    ACCOUNTANT: 'SUBMIT',
    PARENT: 'SUBMIT',
    STUDENT: 'SUBMIT',
  },
  ROLES: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'EDIT',
    VICE_PRINCIPAL: 'VIEW',
    SCHOOL_ADMIN: 'EDIT',
    ORG_ADMIN: 'APPROVE',
    TEACHER: 'NONE',
    ACCOUNTANT: 'NONE',
    HR_MANAGER: 'VIEW',
    PARENT: 'NONE',
    STUDENT: 'NONE',
  },
  REPORTS: {
    SUPER_ADMIN: 'FINALIZE',
    PRINCIPAL: 'EXPORT',
    VICE_PRINCIPAL: 'EXPORT',
    SCHOOL_ADMIN: 'EXPORT',
    ORG_ADMIN: 'EXPORT',
    FINANCE_MANAGER: 'EXPORT',
    ACCOUNTANT: 'EXPORT',
    HR_MANAGER: 'EXPORT',
    TEACHER: 'VIEW',
    FACULTY: 'VIEW',
    PARENT: 'VIEW',
    STUDENT: 'VIEW',
  },
};

/**
 * Resolves standard access level for a role in a specific domain module
 */
export function getModuleAccessLevel(role: string, module: string): AccessLevel {
  const moduleMatrix = CENTRAL_MODULE_ACCESS_MATRIX[module.toUpperCase()];
  if (!moduleMatrix) return 'NONE';
  return moduleMatrix[role.toUpperCase()] || 'NONE';
}

// --- CANONICAL GRANULAR PERMISSIONS VOCABULARY ---
export const CANONICAL_PERMISSIONS = [
  'student.read', 'student.create', 'student.update', 'student.archive',
  'guardian.read', 'guardian.create', 'guardian.update',
  'attendance.read', 'attendance.create', 'attendance.update', 'attendance.lock',
  'class.read', 'class.create', 'class.update',
  'section.read', 'section.create', 'section.update',
  'subject.read', 'subject.create', 'subject.update',
  'exam.read', 'exam.create', 'exam.update', 'exam.publish',
  'result.read', 'result.create', 'result.update', 'result.publish',
  'fee.read', 'fee.create', 'fee.update',
  'payment.read', 'payment.create', 'payment.reverse',
  'receipt.read', 'receipt.create',
  'staff.read', 'staff.create', 'staff.update',
  'payroll.read', 'payroll.create', 'payroll.approve',
  'document.read', 'document.upload', 'document.verify', 'document.download',
  'report.read',
  'account.read', 'account.create', 'account.update', 'account.disable', 'account.delete',
  'role.read', 'role.create', 'role.update',
  'audit.read',
  'settings.read', 'settings.update',
] as const;

export const PERMISSION_ALIASES: Record<string, string[]> = {
  'student.read': ['students.view', 'students.view_own', 'student.view', 'student.view_own'],
  'student.create': ['students.create', 'admissions.create'],
  'student.update': ['students.update'],
  'student.archive': ['students.archive', 'students.delete'],
  'guardian.read': ['guardians.view', 'parents.view'],
  'guardian.create': ['guardians.create', 'parents.create'],
  'guardian.update': ['guardians.update', 'parents.update'],
  'attendance.read': ['attendance.view', 'attendance.view_own'],
  'attendance.create': ['attendance.mark'],
  'attendance.update': ['attendance.correct'],
  'attendance.lock': ['attendance.approve', 'attendance.finalize'],
  'class.read': ['academics.view', 'classes.view'],
  'class.create': ['academics.manage', 'classes.create'],
  'class.update': ['academics.manage', 'classes.update'],
  'section.read': ['academics.view', 'sections.view'],
  'section.create': ['academics.manage', 'sections.create'],
  'section.update': ['academics.manage', 'sections.update'],
  'subject.read': ['academics.view', 'subjects.view'],
  'subject.create': ['academics.manage', 'subjects.create'],
  'subject.update': ['academics.manage', 'subjects.update'],
  'exam.read': ['examinations.view', 'examinations.view_own'],
  'exam.create': ['examinations.create'],
  'exam.update': ['examinations.review'],
  'exam.publish': ['examinations.publish'],
  'result.read': ['examinations.view', 'examinations.view_own'],
  'result.create': ['examinations.enter_marks', 'marks.enter'],
  'result.update': ['examinations.enter_marks', 'marks.enter'],
  'result.publish': ['examinations.publish'],
  'fee.read': ['fees.view', 'fees.view_own'],
  'fee.create': ['fees.create', 'fees.adjust'],
  'fee.update': ['fees.adjust', 'fees.refund', 'fees.approve'],
  'payment.read': ['fees.view', 'fees.receipt', 'fees.view_own'],
  'payment.create': ['fees.collect'],
  'payment.reverse': ['fees.refund', 'fees.adjust'],
  'receipt.read': ['fees.receipt', 'fees.view', 'fees.view_own'],
  'receipt.create': ['fees.receipt', 'fees.collect'],
  'staff.read': ['staff.view'],
  'staff.create': ['staff.create'],
  'staff.update': ['staff.update', 'staff.assign_responsibility', 'staff.transfer', 'staff.provision_account'],
  'payroll.read': ['staff.view_sensitive_hr', 'payroll.view'],
  'payroll.create': ['payroll.manage'],
  'payroll.approve': ['approvals.act', 'payroll.approve'],
  'document.read': ['staff.verify_document', 'documents.view'],
  'document.upload': ['documents.upload', 'staff.upload_document'],
  'document.verify': ['staff.verify_document'],
  'document.download': ['documents.download', 'reports.export'],
  'report.read': ['reports.view', 'reports.export'],
  'account.read': ['staff.view', 'roles.view', 'accounts.view'],
  'account.create': ['staff.provision_account', 'accounts.create'],
  'account.update': ['staff.provision_account', 'accounts.update'],
  'account.disable': ['staff.provision_account', 'accounts.disable'],
  'account.delete': ['staff.provision_account', 'accounts.delete', 'roles.manage'],
  'role.read': ['roles.view'],
  'role.create': ['roles.manage'],
  'role.update': ['roles.manage'],
  'audit.read': ['audit.view'],
  'settings.read': ['license.view', 'settings.view'],
  'settings.update': ['settings.manage', 'license.manage'],
};

/**
 * Normalizes a permission to its canonical representation
 */
export function toCanonicalPermission(perm: string): string {
  if ((CANONICAL_PERMISSIONS as readonly string[]).includes(perm)) {
    return perm;
  }
  for (const [canonical, aliases] of Object.entries(PERMISSION_ALIASES)) {
    if (aliases.includes(perm)) return canonical;
  }
  return perm;
}

/**
 * Checks if a granted permission satisfies the requested permission
 * Handles wildcards ('*', 'student.*') and legacy aliases bidirectionally.
 */
export function matchesPermission(grantedPerm: string, requestedPerm: string): boolean {
  if (grantedPerm === '*' || grantedPerm === requestedPerm) return true;

  const [grantedDomain] = grantedPerm.split('.');
  const [reqDomain] = requestedPerm.split('.');

  if (grantedPerm === `${grantedDomain}.*` && grantedDomain === reqDomain) {
    return true;
  }

  // Canonical alias checks
  const canonicalRequested = toCanonicalPermission(requestedPerm);
  const canonicalGranted = toCanonicalPermission(grantedPerm);

  if (canonicalGranted === canonicalRequested) return true;

  // Wildcard check on canonical domain
  const [canGrantedDomain] = canonicalGranted.split('.');
  const [canReqDomain] = canonicalRequested.split('.');
  if (grantedPerm === `${canGrantedDomain}.*` && canGrantedDomain === canReqDomain) {
    return true;
  }

  // Check alias sets
  for (const [canonical, aliases] of Object.entries(PERMISSION_ALIASES)) {
    const isGrantedMatching = grantedPerm === canonical || aliases.includes(grantedPerm);
    const isRequestedMatching = requestedPerm === canonical || aliases.includes(requestedPerm);
    if (isGrantedMatching && isRequestedMatching) return true;
  }

  return false;
}

export const ALL_PERMISSIONS = Array.from(
  new Set([...Object.keys(ACTION_DEFINITIONS), ...CANONICAL_PERMISSIONS])
);
